# Airflow 3.1.8 + отдельное окружение dbt (dbt и Airflow имеют конфликтующие зависимости)
FROM apache/airflow:3.1.8-python3.11

USER root
RUN apt-get update \
 && apt-get install -y --no-install-recommends postgresql-client \
 && rm -rf /var/lib/apt/lists/* \
 && python -m venv /opt/dbt-venv \
 && /opt/dbt-venv/bin/pip install --no-cache-dir "dbt-core==1.10.13" "dbt-postgres==1.10.0" \
 && chown -R airflow: /opt/dbt-venv
USER airflow
