spark.master local[*]
spark.driver.memory 2g
spark.ui.port 4040

spark.sql.extensions org.apache.iceberg.spark.extensions.IcebergSparkSessionExtensions

spark.sql.catalog.lakehouse org.apache.iceberg.spark.SparkCatalog
spark.sql.catalog.lakehouse.catalog-impl org.apache.iceberg.jdbc.JdbcCatalog
spark.sql.catalog.lakehouse.uri jdbc:postgresql://postgres:5432/iceberg_catalog
spark.sql.catalog.lakehouse.jdbc.user iceberg
spark.sql.catalog.lakehouse.jdbc.password iceberg
spark.sql.catalog.lakehouse.warehouse s3a://datalake/warehouse
spark.sql.catalog.lakehouse.io-impl org.apache.iceberg.aws.s3.S3FileIO
spark.sql.catalog.lakehouse.s3.endpoint http://minio:9000
spark.sql.catalog.lakehouse.s3.region us-east-1
spark.sql.catalog.lakehouse.s3.path-style-access true
spark.sql.catalog.lakehouse.s3.access-key-id admin
spark.sql.catalog.lakehouse.s3.secret-access-key hse2026minio

spark.hadoop.fs.s3a.access.key admin
spark.hadoop.fs.s3a.secret.key hse2026minio
spark.hadoop.fs.s3a.endpoint http://minio:9000
spark.hadoop.fs.s3a.path.style.access true
spark.hadoop.fs.s3a.connection.ssl.enabled false
spark.hadoop.fs.s3a.impl org.apache.hadoop.fs.s3a.S3AFileSystem
